---
#Ansible Playbook to configure Cisco IOS interface description

- name: Set Cisco IOS Interface Description
  hosts: cisco_routers
  
  tasks:
    - name: Replaces description listed interfaces with provided description
      cisco.ios.ios_interfaces:
        config:
        - name: GigabitEthernet0/3
          description: New Interface Description
        state: replaced